# Generated by Django 5.2.17 on 2026-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litige',
            name='date_limite_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='date_reponse_vendeur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='reponse_vendeur',
            field=models.TextField(blank=True),
        ),
    ]
