# Generated by Django 5.2.17 on 2026-08-31 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptee'), ('REFUSEE', 'Refusee')], default='EN_ATTENTE', max_length=12)),
                ('commentaire_decision', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_arbitrees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de modification',
                'verbose_name_plural': 'demandes de modification',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_push', models.BooleanField(default=True)),
                ('courriels_promotionnels', models.BooleanField(default=False)),
                ('densite', models.CharField(choices=[('COMPACTE', 'Compacte'), ('NORMALE', 'Normale')], default='NORMALE', max_length=10)),
                ('masquer_montants', models.BooleanField(default=False, help_text="Cache les montants a l'ecran, utile en public.")),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferences',
                'verbose_name_plural': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='ChampDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(choices=[('NOM', 'Nom'), ('PRENOM', 'Prenom'), ('DATE_NAISSANCE', 'Date de naissance')], max_length=20)),
                ('valeur_actuelle', models.CharField(blank=True, max_length=150)),
                ('valeur_demandee', models.CharField(max_length=150)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='comptes.demandemodification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('demande', 'champ'), name='un_champ_par_demande')],
            },
        ),
    ]
