# Generated by Django 5.2.17 on 2026-09-04 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_demandemodification_preferences_champdemande'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=15)),
                ('quatre_derniers', models.CharField(max_length=4)),
                ('mois_expiration', models.PositiveSmallIntegerField()),
                ('annee_expiration', models.PositiveSmallIntegerField()),
                ('jeton', models.CharField(max_length=64, unique=True)),
                ('par_defaut', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_paiement', to='comptes.client')),
            ],
            options={
                'verbose_name': 'moyen de paiement',
                'verbose_name_plural': 'moyens de paiement',
                'ordering': ['-par_defaut', '-date_ajout'],
            },
        ),
    ]
