# Generated by Django 5.2.17 on 2026-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_reservation_de_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatut',
            name='type_objet',
            field=models.CharField(choices=[('COMMANDE', 'Commande'), ('SOUS_COMMANDE', 'Sous-commande'), ('LIVRAISON', 'Livraison')], max_length=14),
        ),
    ]
