# Generated by Django 5.2.17 on 2026-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_photoproduit_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
