# Generated by Django 5.2.17 on 2026-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_apercu_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_est_illustration',
            field=models.BooleanField(default=False),
        ),
    ]
